/* eslint-disable cypress/no-unnecessary-waiting */
describe("Miscellaneous extras", { testIsolation: false }, () => {
  beforeEach(() => {
    cy.intercept("rg2api.php?type=event&id=*").as("event")
    cy.intercept("rg2api.php?type=events*").as("events")
  })
  it("should handle an invalid URL ID and just display the event list", () => {
    cy.task("setUpKartat", { config: "config-01" })
    cy.visit("http://localhost/rg2/#xyz")
    cy.wait("@events")
    cy.get("#course-tab").should("be.disabled")
    cy.get("#result-tab").should("be.disabled")
    cy.get("#draw-tab").should("be.disabled")
    cy.location("hash").should("eq", "#")
    cy.visit("http://localhost/rg2/#0")
    cy.location("hash").should("eq", "#")
    cy.visit("http://localhost/rg2/#xyz10")
    cy.location("hash").should("eq", "#10")
  })
  it("should load a normal event from a URL with routes and courses", () => {
    cy.task("setUpKartat", { config: "config-01" })
    cy.visit("http://localhost/rg2/#388&course=2,5&route=50002,50075")
    cy.wait("@event")
    cy.get("#course-tab").should("not.be.disabled")
    cy.get("#course-tab").click()
    cy.get("#rg2-course-table .showcourse[data-courseid='1']").should("not.be.checked")
    cy.get("#rg2-course-table .showcourse[data-courseid='2']").should("be.checked")
    cy.get("#rg2-course-table .showcourse[data-courseid='3']").should("not.be.checked")
    cy.get("#rg2-course-table .showcourse[data-courseid='4']").should("not.be.checked")
    cy.get("#rg2-course-table .showcourse[data-courseid='5']").should("be.checked")
    cy.get("#result-tab").should("not.be.disabled")
    cy.get(".showtrack[data-id='50002']").should("be.checked")
    cy.get(".showtrack[data-id='50075']").should("be.checked")
    cy.get(".showtrack[data-id='50009']").should("not.be.checked")
    cy.get(".showtrack[data-id='50076']").should("not.be.checked")
    cy.get("#draw-tab").should("not.be.disabled")
    cy.get("#rg2-event-title").should("contain", "2022-06-04 Highfield Park Saturday Series")
    cy.get("#btn-about").click()
    cy.get("#rg2-event-stats").should("not.be.empty").and("contain", "Highfield Park Saturday Series")
    cy.get("#rg2-right-info-panel").find(".btn-close").click()
  })
  it("should load another event and go backwards and forwards", () => {
    cy.task("setUpKartat", { config: "config-01" })
    cy.visit("http://localhost/rg2/#380")
    cy.wait("@event")
    cy.get("#rg2-event-title").should("contain", "2021-12-26 Trent Park Boxing Day Score")
    cy.get("#btn-about").click()
    cy.get("#rg2-event-stats").should("not.be.empty").and("contain", "Trent Park Boxing Day Score")
    cy.visit("http://localhost/rg2/#388")
    cy.wait("@event")
    cy.get("#rg2-event-title").should("contain", "2022-06-04 Highfield Park Saturday Series")
    cy.go("back")
    cy.wait("@event")
    cy.get("#rg2-event-title").should("contain", "2021-12-26 Trent Park Boxing Day Score")
    cy.go("forward")
    cy.wait("@event")
    cy.get("#rg2-event-title").should("contain", "2022-06-04 Highfield Park Saturday Series")
  })
  it("reports network errors getting Grid and Chart", () => {
    // network error on deferred load of Grid and Chart when accessing stats
    cy.intercept("@ag-grid-community_core.js?v=*", { forceNetworkError: true }).as("statsError")
    cy.get("#btn-stats").click()
    cy.wait("@statsError").should("have.property", "error")
    cy.closeWarningDialog("Error loading Grid and Chart")
  })
  it("reports missing map files", () => {
    cy.visit("http://localhost/rg2/#387")
    cy.closeWarningDialog("The map for this event could not be loaded.")
  })
  it("reports network errors on GET call to API", () => {
    cy.intercept("rg2api.php?type=event&id=*", { forceNetworkError: true }).as("error")
    cy.visit("http://localhost/rg2/#380")
    cy.wait("@error").should("have.property", "error")
    cy.closeWarningDialog("Configuration error")
  })
  it("reports an invalid kartat directory", () => {
    cy.task("setUpKartat", { config: "config-02", php: "config-02" })
    cy.visit("http://localhost/rg2/")
    cy.get("body").should("be.visible").and("contain", "Routegadget 2: Kartat directory").and("contain", "not found")
  })
})
