import manager from "../../fixtures/validmanager.json"
describe("Event creation 1", { testIsolation: false }, () => {
  before(() => {
    cy.task("setUpKartat", { config: "config-01" })
  })
  it("should allow login", () => {
    cy.intercept("rg2api.php?type=events*").as("events")
    cy.intercept("rg2api.php?type=login*").as("login")
    cy.visit("http://localhost/rg2/?manage")
    cy.wait("@events")
    cy.get("#rg2-user-name").clear().type(manager.name)
    cy.get("#rg2-password").clear().type(manager.password)
    cy.get("#btn-login").click()
    cy.wait("@login")
  })
  it("should warn about incorrect details", () => {
    cy.get("#manage-create-tab").click()
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("Event name is not valid")
    cy.get("#rg2-event-name").clear().type("Highfield Park Saturday Series")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("No map selected")
    cy.get("#rg2-select-map").select("402: Highfield")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("Club name is not valid")
    cy.get("#rg2-select-club-name").clear().type("HH")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("Date is not valid")
    cy.get("#rg2-select-event-date").clear().type("2022-06-04")
    cy.get("#rg2-enter-event-comments").clear().type("Highfield Park normal event")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("Event level is not valid")
    cy.get("#rg2-select-event-level").select("L")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("No course information")
    cy.selectCourseFile("miltonriggIOFV2results.xml", "File is not a valid XML course file")
    cy.selectCourseFile("miltonriggIOFV3courses.xml", "Your course file does not match the map co-ordinates")
    cy.closeModal("Course details")
    cy.selectCourseFile("Highfield-2022-06-04-v7.xml")
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("No results information")
    cy.selectResultsFile("ellenbrook.jgw", "Results file type is not recognised")
    cy.selectResultsFile("miltonriggIOFV1results.xml", "Invalid IOF file format. Version 1.0 not supported")
    cy.selectResultsFile(
      "miltonriggIOFV2invalidresults.xml",
      "File is not a valid XML results file. ResultList element missing"
    )
    cy.selectResultsFile("IOFV2resultsparseerror.xml", "Error processing XML file")
    cy.selectResultsFile("IOFV3resultsparseerror.xml", "Error processing XML file")
    cy.selectResultsFile("miltonriggIOFV3courses.xml", "File is not a valid XML results file")
    cy.selectResultsFile("miltonriggIOFV2results.xml")
    cy.selectResultsFile("miltonriggIOFV3results.xml")
    cy.selectResultsFile("spklasse.csv")
    cy.selectResultsFile("highfield4RG.csv")
  })
  it("should allow you to cancel creating an event", () => {
    cy.get("#btn-create-event").click()
    cy.closeModal("Confirm event creation", ".modal-footer button[data-bs-dismiss='modal'")
  })
  it("should create an event", () => {
    cy.createEvent()
  })
})
