import manager from "../../fixtures/validmanager.json"
describe("Event creation 2", { testIsolation: false }, () => {
  before(() => {
    cy.task("setUpKartat", { config: "config-01" })
  })
  beforeEach(() => {
    cy.intercept("rg2api.php?type=event&id=*").as("event")
    cy.intercept("rg2api.php?type=events*").as("events")
    cy.intercept("rg2api.php?type=login*").as("login")
    cy.intercept("rg2api.php?type=maps*").as("maps")
  })
  it("should allow login", () => {
    cy.visit("http://localhost/rg2/?manage")
    cy.wait("@events")
    cy.get("#rg2-user-name").clear().type(manager.name)
    cy.get("#rg2-password").clear().type(manager.password)
    cy.get("#btn-login").click()
    cy.wait("@login")
  })
  it("should create an event with IOF XML v2 results", () => {
    cy.addMap("Ellenbrook georef", "ellenbrook.jpg", "ellenbrook.jgw")
    cy.get("#manage-create-tab").click()
    cy.get("#rg2-event-name").clear().type("Ellenbrook Saturday Series")
    cy.get("#rg2-select-map").select("404: Ellenbrook georef")
    cy.get("#rg2-select-club-name").clear().type("HH")
    cy.get("#rg2-select-event-date").clear().type("2022-06-04")
    cy.get("#rg2-enter-event-comments").clear()
    cy.get("#rg2-select-event-level").select("T")
    cy.selectCourseFile("ellenbrookIOFV1courses.xml", "Invalid IOF file format. Version 1.0.0 not supported")
    cy.selectCourseFile(
      "ellenbrookIOFV2invalidcourses.xml",
      "File is not a valid XML course file. CourseData element missing"
    )
    cy.selectResultsFile("ellenbrook.csv")
    cy.selectCourseFile("ellenbrookIOFV2Georefcourses.xml")
    cy.createEvent()
  })
  it("should create a JK Relay", () => {
    cy.addMap("Pwll Ddu georef", "pwllddu.jpg", "pwllddu.jgw")
    cy.get("#manage-create-tab").click()
    cy.get("#rg2-event-name").clear().type("JK2014 Relays: Pwll Ddu")
    cy.get("#rg2-select-map").select("405: Pwll Ddu georef")
    cy.get("#rg2-select-club-name").clear().type("WOA")
    cy.get("#rg2-select-event-date").clear().type("2014-04-21")
    cy.get("#rg2-enter-event-comments").clear("JK Relay example")
    cy.get("#rg2-select-event-level").select("I")
    cy.selectCourseFile("pwlldduIOFV3relay.xml")
    cy.selectResultsFile("pwllddu.csv")
    cy.get("#chk-score-event").click()
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("Controls have not been adjusted")
  })
  it("should allow you to adjust controls", () => {
    // drag controls
    cy.get("#rg2-map-canvas")
      .trigger("mousedown", 700, 400, { button: 0 })
      .trigger("mousemove", 750, 450)
      .trigger("mouseup", 750, 450, { button: 0 })
    // drag controls and map if locked from checkbox
    cy.get("#chk-move-map-and-controls").check()
    cy.get("#rg2-map-canvas")
      .trigger("mousedown", 700, 400, { button: 0 })
      .trigger("mousemove", 750, 450)
      .trigger("mouseup", 750, 450, { button: 0 })
    cy.get("#chk-move-map-and-controls").uncheck()
    // drag controls and map if dragged with right click
    cy.get("#rg2-map-canvas")
      .trigger("mousedown", 700, 400, { button: 2 })
      .trigger("mousemove", 750, 450)
      .trigger("mouseup", 750, 450, { button: 2 })
    cy.createEvent()
  })
  it("should create an event with no results and a drawn course", () => {
    cy.get("#manage-create-tab").click()
    cy.get("#rg2-event-name").clear().type("Jersey Farm Street-O")
    cy.get("#rg2-select-map").select("126: Jersey Farm")
    cy.get("#rg2-select-club-name").clear().type("HH")
    cy.get("#rg2-select-event-date").clear().type("2022-07-11")
    cy.get("#rg2-enter-event-comments").clear()
    cy.get("#rg2-select-event-level").select("L")
    cy.get("#chk-no-results").click()
    cy.get("#btn-create-event").click()
    cy.closeWarningDialog("No course information")
    cy.get("#btn-draw-courses").click()
    cy.get("#rg2-new-course-name").clear().type("45 minute score")
    // draw start and finish
    cy.get("#rg2-map-canvas")
      .trigger("mousedown", 700, 400)
      .trigger("mouseup", 700, 400)
      .trigger("mousedown", 700, 400)
      .trigger("mouseup", 700, 400)
    cy.createEvent()
  })
  it("should display the new events", () => {
    cy.visit("http://localhost/rg2")
    cy.wait("@events")
  })
  it("should upload a tcx file to the newly created Ellenbrook event", () => {
    cy.get("#rg2-event-table  > tr[data-kartatid='389']").click()
    cy.wait("@event")
    cy.get("#draw-tab").click()
    cy.get("#rg2-select-course").select("Light Green")
    cy.get("#rg2-select-name").select("30:09 David Dixon")
    cy.get("#rg2-load-gps-file").selectFile("./cypress/fixtures/data/ellenbrook.tcx")
    cy.get("#btn-save-gps-route").click()
    cy.wait("@event")
    cy.closeWarningDialog("Your route has been saved")
  })
})
